name: DNN-based_source_separation_musdb18

channels:
  - defaults
  - pytorch
  - conda-forge

dependencies:
  - python>=3.6,<=3.8
  - numpy>=1.19
  - matplotlib>=3.3.2
  - pytorch>=1.8.0
  - torchaudio>=0.8.0
  - cudatoolkit>=10
  - pip
  - pip:
    - musdb==0.4.0
    - museval==0.4.0